// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoDismissController from "./auto_dismiss_controller"
application.register("auto-dismiss", AutoDismissController)

import BadgeSelectController from "./badge_select_controller"
application.register("badge-select", BadgeSelectController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProfileImageController from "./profile_image_controller"
application.register("profile-image", ProfileImageController)

import QuizScrollController from "./quiz_scroll_controller"
application.register("quiz-scroll", QuizScrollController)

import TopController from "./top_controller"
application.register("top", TopController)

import HomeController from "./home_controller"
application.register("home", HomeController)
