// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

// クイズ画面のスクロール
import QuizScrollController from "./quiz_scroll_controller"
application.register("quiz-scroll", QuizScrollController)

// ユーザーアイコン画像のプレビュー
import ProfileImageController from "./profile_image_controller"
application.register("profile-image", ProfileImageController)

// トースト・フラッシュメッセージの自動消去
import AutoDismissController from "./auto_dismiss_controller"
application.register("auto-dismiss", AutoDismissController)
